{{- if eq .Values.secrets.type "externalSecret" }}
{{- if include "wrapper.cacheEnabled" . }}
---
{{ include "wrapper.externalSecret" (dict "root" . "name" "nextcloud-redis" "keys" (list "redis-password") "static" (dict "redis-host" "nextcloud-redis")) }}
{{- end }}
{{- if .Values.whiteboard.enabled }}
---
{{ include "wrapper.externalSecret" (dict "root" . "name" "nextcloud-whiteboard" "keys" (list "whiteboard-jwt-secret")) }}
{{- end }}
{{- if .Values.talk.enabled }}
---
{{ include "wrapper.externalSecret" (dict "root" . "name" "nextcloud-talk" "keys" (list "signaling-secret" "signaling-internal-secret" "signaling-hashkey" "signaling-blockkey" "recording-secret" "turn-secret")) }}
{{- end }}
{{- if .Values.monitoring.enabled }}
---
{{ include "wrapper.externalSecret" (dict "root" . "name" "nextcloud-metrics" "keys" (list "metrics-token")) }}
{{- end }}
{{- end }}
