apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nextcloud
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ include "wrapper.host" . }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: nextcloud
    weight: 100
  wildcardPolicy: None
