apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bifrost
  {{- if and .Values.route.hostname .Values.route.annotations }}
  annotations:
    {{- toYaml .Values.route.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.hostname }}
  host: {{ .Values.route.hostname }}
  {{- end }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: bifrost
    weight: 100
  wildcardPolicy: None
