apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailu-wrapper.fullname" . }}-front-dovecot
data:
  # no chroot: the pod has no SYS_CHROOT capability
  proxy.conf: |
    service imap-login {
      chroot =
    }
    service pop3-login {
      chroot =
    }
    service managesieve-login {
      chroot =
    }
    service submission-login {
      chroot =
    }
    service anvil {
      chroot =
    }
