{{- if .Values.dns.enabled }}
{{- $domain := .Values.upstream.domain }}
# TXT targets carry their own quotes: the DNS provider stores them that way
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ include "mailu-wrapper.fullname" . }}
spec:
  endpoints:
  - dnsName: {{ $domain }}
    recordType: TXT
    recordTTL: {{ .Values.dns.ttl }}
    targets:
    - {{ printf "%q" .Values.dns.spf | quote }}
  - dnsName: {{ printf "_dmarc.%s" $domain }}
    recordType: TXT
    recordTTL: {{ .Values.dns.ttl }}
    targets:
    - {{ printf "%q" .Values.dns.dmarc | quote }}
{{- end }}
