{{- if eq .Values.secrets.type "externalSecret" }}
{{- $store := required "secrets.externalSecret.storeName is required" .Values.secrets.externalSecret.storeName }}
{{- if and .Values.source.gitRepo .Values.source.private }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mkdocs.fullname" . }}-git
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecret.storeKind }}
    name: {{ $store }}
  target:
    name: {{ include "mkdocs.fullname" . }}-git
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: {{ .Values.source.gitUsername | quote }}
        password: {{ "{{ .password }}" | quote }}
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.secrets.externalSecret.items.gitPassword }}
      property: login.password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
---
{{- end }}
{{- if and .Values.source.gitRepo .Values.source.webhook }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mkdocs.fullname" . }}-webhook
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecret.storeKind }}
    name: {{ $store }}
  target:
    name: {{ include "mkdocs.fullname" . }}-webhook
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: WebHookSecretKey
    remoteRef:
      key: {{ .Values.secrets.externalSecret.items.webhookSecret }}
      property: login.password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
---
{{- end }}
{{- if .Values.oauth.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mkdocs.fullname" . }}-oauth
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecret.storeKind }}
    name: {{ $store }}
  target:
    name: {{ include "mkdocs.fullname" . }}-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: client-secret
    remoteRef:
      key: {{ .Values.secrets.externalSecret.items.clientSecret }}
      property: login.password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: cookie-secret
    remoteRef:
      key: {{ .Values.secrets.externalSecret.items.cookieSecret }}
      property: login.password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
{{- end }}
{{- end }}
