apiVersion: v1
kind: Service
metadata:
  name: {{ include "mkdocs.fullname" . }}
spec:
  selector:
    app: {{ include "mkdocs.fullname" . }}
  ports:
  - name: http
    port: 80
    targetPort: {{ if .Values.oauth.enabled }}4180{{ else }}8080{{ end }}
