{{- if eq .Values.secrets.type "kubernetes" }}
{{- $found := lookup "v1" "Secret" .Release.Namespace "nexus-credentials" }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-credentials
type: Opaque
data:
  {{- if .Values.secrets.adminPassword }}
  admin-password: {{ .Values.secrets.adminPassword | b64enc | quote }}
  {{- else if $found }}
  admin-password: {{ index $found.data "admin-password" | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- else }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-credentials
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecret.storeKind }}
    name: {{ required "secrets.externalSecret.storeName is required" .Values.secrets.externalSecret.storeName }}
  target:
    name: nexus-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: admin-password
    remoteRef:
      key: {{ .Values.secrets.externalSecret.item }}
      property: login.password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
{{- end }}
