{{- if .Values.build.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "omniroute.fullname" . }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.build.gitRepo }}
      ref: {{ .Values.build.gitRef }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.build.dockerfilePath }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "omniroute.fullname" . }}:latest
  resources:
    {{- toYaml .Values.build.resources | nindent 4 }}
  triggers:
    - type: ConfigChange
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
{{- end }}
