{{- if eq .Values.secrets.type "externalSecret" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "omniroute.fullname" . }}-secret
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecret.storeKind }}
    name: {{ required "secrets.externalSecret.storeName is required" .Values.secrets.externalSecret.storeName }}
  target:
    name: {{ include "omniroute.fullname" . }}-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  {{- range $key, $item := .Values.secrets.externalSecret.items }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $item }}
      property: login.password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
  {{- end }}
{{- end }}
