apiVersion: v2
name: mailu
description: Mail server with SMTP, IMAP, webmail, spam filter and admin interface
type: application
version: 0.1.0
appVersion: "2024.06.46"
home: https://apps.openshift.eu
icon: https://mailu.io/master/_images/logo.png
keywords:
- mail
- email
- smtp
- imap
- webmail
sources:
- https://github.com/Mailu/helm-charts
- https://github.com/hoolia/apps.openshift.eu
maintainers:
- name: Hoolia B.V.
  url: https://apps.openshift.eu
annotations:
  charts.openshift.io/name: Mailu
  charts.openshift.io/provider: Hoolia B.V.
dependencies:
- name: mailu
  alias: upstream
  version: 2.6.3
  repository: https://mailu.github.io/helm-charts
